### ISSUE TITLE
Update discord_emojis.json

### ISSUE THREAD

**Issue by micwoj92** [terminal-discord/discord-emoji#2]
I've seen more complete versions of the file on the internet, but I don't know how to generate it so I don't know if they are latest version available.

**Comment by Noskcaj19** [comment]
Thanks for pointing out that it's now out of date.  I've updated the emoji list and added instructions to the README.
It's rather simplistic, but I figure the list doesn't change too frequently so I just manually search for the list in the code.
Hopefully that helps
